/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppDisplayBookmarks {
        "bookmarks": any;
        "deleteData": (...args: any)=>any;
        "searchTerm": any;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppDisplayBookmarksElement extends Components.AppDisplayBookmarks, HTMLStencilElement {
    }
    var HTMLAppDisplayBookmarksElement: {
        prototype: HTMLAppDisplayBookmarksElement;
        new (): HTMLAppDisplayBookmarksElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-display-bookmarks": HTMLAppDisplayBookmarksElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppDisplayBookmarks {
        "bookmarks"?: any;
        "deleteData"?: (...args: any)=>any;
        "searchTerm"?: any;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-display-bookmarks": AppDisplayBookmarks;
        "app-home": AppHome;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-display-bookmarks": LocalJSX.AppDisplayBookmarks & JSXBase.HTMLAttributes<HTMLAppDisplayBookmarksElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
